### PR TITLE
[Mod Element] Custom Element

### PR DESCRIPTION
**Pull request by ghost**
**Version:-** 0.X.X

### Changes
New file "code.definition.yaml" at "src/fabric-1.15.2/"
New file "code.java.ftl" at "src/fabric-1.15.2/templates"

**Note:** First of all I don't really understand how GitHub works so sorry if this is in the wrong category. This is something small but I think custom elements are very important and I couldn't see it in the to do list. I searched about fabric through its maven but I honestly couldn't understand some of the things, it looks like it doesn't have starting or setup events like forge does or I'm just blind, so it doesn't have any imports. It just creates a new class according to the elements name just like official MCreator generators.

Download: [Custom Element.zip](https://github.com/ClothCreators/MCreatorFabricGenerator/files/4925039/Custom.Element.zip

### CODE REVIEW

**Comment by ghost** [comment]
Could you explain what is the problem?

**Comment by BoogieMonster1O1** [comment]
Hey! We appreciate your effort to contribute, but there is a problem. We can't merge the changes :(

First fork this repository. We can't merge any changes without you forking the repository. From Github, You can directly edit the files or create new ones in the forked repository. Once you know it works, click on the `Pull Request` button. It should look somewhat like this.  
Screen Shot 2020-07-15 at 6 15 57 PM.  
You should automatically be redirected where you can write your pull request message. 

I'm closing this for now. Thank you for all your effort!

**Review by CrispyChips6660 — COMMENTED** [review]
@NOYBss this.... isn't how you do a pull request. You don't give a *download* link for your contributed code, you *fork* the code(copy a version of the repo using the fork button) and make your changes in your version. Then, you create a pull request that requests to merge your fork/version of this repo into the main one (ours). (Why are you trying to merge 1.15 to 1.16 :P)
[I think you should read this before contributing](https://codeburst.io/git-and-github-in-a-nutshell-b0a3cc06458f)

**Comment by CrispyChips6660** [comment]
we replied at the same time :P

**Comment by ghost** [comment]
Thanks for the info, I don't understand GitHub very much. I'll read the link you gave and open a pull request according to that.

**Pull request closed without merging**
