### PR TITLE
2020.5 Compatibility

### LINKED ISSUE #75: [Request] Comaptibility with 2020.5 3rd snapshot
**Describe the feature**
Apply template similar to https://github.com/MCreator/Generator-Forge-1.12.2/pull/14 for compatibility with https://github.com/MCreator/MCreator/pull/267 when 2020.5 3rd snapshot gets implemented.

NOTE: PR might change and the format of this template might change as it was not merged yet, this is more of a future notice so it does not get forgotten.

### PR DESCRIPTION
**Pull request by BoogieMonster1O1**

### CODE REVIEW

**Comment by KlemenDEV** [comment]
Linked issue: #75

**Comment by Goldorion** [comment]
Biomes have been updated for the second 2020.5 snapshot. However, features (except default features) are missing.

**Comment by KlemenDEV** [comment]
If biomes use JSON, could they be merged into Forge 1.16.4 generator too?

**Comment by BoogieMonster1O1** [comment]
> If biomes use JSON, could they be merged into Forge 1.16.4 generator too?

biomes don’t use json
there are lots of bugs with them and it would be easier to add the biomes to the world generator or add ores to them if they’re written in code

**Pull request merged**
