### PR TITLE
[New Mod Element] Custom Element

### PR DESCRIPTION
**Pull request by ghost**
**Version:-** 0.6.2

### Changes
Created new file "code.definition.yaml" at "src/fabric-1.15.2/"
Created new file "code.java.ftl" at "src/fabric-1.15.2/templates"

**Note:** This time I forked the repository and commited my changes. I hope it is fine this time.

### CODE REVIEW

**Review by CrispyChips6660 — DISMISSED** [review]
I don't think [this](https://github.com/ClothCreators/MCreatorFabricGenerator/pull/43/commits/f433544bda232069f4a98a974c31d919f57d6167#diff-ab01110217c89957fa14bc72d01fd460R23) is going to work. Why are you extending the mod element class when this generator doesn't have a mod element class?
And why are you adding the mod element annotation when this generator doesn't have that annotation?
I get the feeling that you directly copied this from the forge generator :P

**Review by CrispyChips6660 — CHANGES_REQUESTED** [review]
Why does it still extend a class that doesn't exist bruh
I get the feeling that you don't know Java D:

**Comment by ghost** [comment]
I put it as a place holder I could change it to a "Item" or a "Block" but I don't know what people gonna make

**Comment by CrispyChips6660** [comment]
> I put it as a place holder I could change it to a "Item" or a "Block" but I don't know what people gonna make

Leave it as a blank class that doesn't extend anything....

**Comment by ghost** [comment]
Ok I'll do like that

**Comment by CrispyChips6660** [comment]
Merged into 1.15.

**Pull request merged**
