### PR TITLE
Fix entity_deal_custom_damage not referencing Player Names (%1$s etc)

### PR DESCRIPTION
**Pull request by hyperdotbat**
- code copied from the Forge base of MCreator

### CODE REVIEW

**Comment by HaipaDev** [comment]
ayo why didnt this get merged for 1.9.11 its such a simple pr

**Comment by hyperdotbat** [comment]
ayo why didnt this get merged for 1.9.11 its such a simple pr @Goldorion

**Comment by Goldorion** [comment]
> ayo why didnt this get merged for 1.9.11 its such a simple pr @Goldorion

I was too lazy to test it 😅

**Comment by hyperdotbat** [comment]
> I was too lazy to test it 😅

oh well, thats fine, Im probably not gonna use MCreator anymore as I am in the process of learning Fabric & Mixins, it aint that hard, just doing *good mixins* is somewhat difficult, but I just wanted to contribute what I can what I noticed was broken or could be introduce ([the File Manager key by id pr](https://github.com/Goldorion/File-Manager-MCreator/pull/58))
You didnt really have to test it, wouldnt do a pull request if I didnt test it myself, works no problem ;)

**Comment by PSGitHubUser1** [comment]
How you learnt Fabric & those Mixins. I wanna learn too.. Can you provide tutorials you used..?

Also, I dont understand that if I want to make a MCreator plugin then how to do like how to even setup the java Workspace for  .ftl file. Sometimes i randomly get motivated and then face the pain that IDK how to do that cool thing..

**Comment by hyperdotbat** [comment]
> Also, I dont understand that if I want to make a MCreator plugin then how to do like how to even setup the java Workspace for  .ftl file. Sometimes i randomly get motivated and then face the pain that IDK how to do that cool thing.. 

For MCreator plugins I also dreaded it, but I didnt even setup any workspace, I just coppied necessary files from a different plugin, their naming is necessary, everything has to be correctly set, digging through, understanding the patterns of what is what, and then I either asked ChatGPT or checked the internet how the code should look like on Fabric
 


> How you learnt Fabric & those Mixins. I wanna learn too.. Can you provide tutorials you used..?

Surprisingly I "didnt", its just been 3 days since Ive started, I just have experience with programming and just went ahead and started (Java is quite similar to C#) and yeah Mixins are a tiny bit weird, but the community on the Discord server is great and they helped a lot!
(I also started programming when I was 14, [games in GameMaker: Studio hahha], good luck, keep it up)

**Comment by PSGitHubUser1** [comment]
> > Also, I dont understand that if I want to make a MCreator plugin then how to do like how to even setup the java Workspace for  .ftl file. Sometimes i randomly get motivated and then face the pain that IDK how to do that cool thing.. 
> 
> For MCreator plugins I also dreaded it, but I didnt even setup any workspace, I just coppied necessary files from a different plugin, their naming is necessary, everything has to be correctly set, digging through, understanding the patterns of what is what, and then I either asked ChatGPT or checked the internet how the code should look like on Fabric
>  
> 
> 
> > How you learnt Fabric & those Mixins. I wanna learn too.. Can you provide tutorials you used..?
> 
> Surprisingly I "didnt", its just been 3 days since Ive started, I just have experience with programming and just went ahead and started (Java is quite similar to C#) and yeah Mixins are a tiny bit weird, but the community on the Discord server is great and they helped a lot!
> (I also started programming when I was 14, [games in GameMaker: Studio hahha], good luck, keep it up)

Bro I am 14.. So its my perfect time to start brooo... also I know many things already because I was interested so I started anything related to 'program', when I was 8 or 9.

**Comment by hyperdotbat** [comment]
> I was too lazy to test it 😅

hahha I saw you implemented #500 but forgot about this again probably XD

**Comment by Goldorion** [comment]
> > I was too lazy to test it 😅
> 
> hahha I saw you implemented #500 but forgot about this again probably XD

Nah... I'm just trying to make the plugin usable... I get almost 10k lines of errors (in the mcreator.log) for the moment 😅

**Comment by Goldorion** [comment]
Thank you for your contribution!

**Comment by PSGitHubUser1** [comment]
What's true structure? I just saw in changelog of 23.4... Wait, that means my  structure will now not get half when loading chunks #423

(just ignore the blue tree in picture.. That was my mistake tho)

**Comment by Goldorion** [comment]
> What's true structure

A structure that uses Minecraft's structure options instead of using a feature that simply place a NBT file (true structure = /locate and many other options, previous structure = no /locate and the many other options). I simply made the structure like the Forge generator now has since 2023.4 (check the news form more info)

**Pull request merged**
