### PR TITLE
Update to FabricItemSettings and add emissive lighting

### PR DESCRIPTION
**Pull request by ghost**
I couldn't tested these in MCreator but they work in Intellij.

### Minor changes
* Updated items to use new FabricItemSettings
* Added emissive rendering option to blocks

### CODE REVIEW

**Comment by ghost** [comment]
Actually I think some elements should be initialized outside the main class
When a lot of elements are created, main class looks like a mess.

**Review by BoogieMonster1O1 — APPROVED** [review]
It would be great if you can test this to ensure it compiles correctly. Looks good to me though :)

**Comment by BoogieMonster1O1** [comment]
Feel free to mark this as ready for you once tested 👍

**Comment by ghost** [comment]
Ok I'll try to test

**Comment by ghost** [comment]
There is a problem with my MCreator, all of my workspaces fail for some reason. This isn't something about Fabric Generator. I'll try to fix it, but right now I'm unable to test it.

**Comment by BoogieMonster1O1** [comment]
> There is a problem with my MCreator, all of my workspaces fail for some reason. This isn't something about Fabric Generator. I'll try to fix it, but right now I'm unable to test it.

Take your time. We can wait :D

**Comment by ghost** [comment]
idk how but I fixed it and I can say that it compiles correctly

> Actually I think some elements should be initialized outside the main class
> When a lot of elements are created, main class looks like a mess.

btw what do you think about this, if you think its okay I could commit it to this pr

**Comment by BoogieMonster1O1** [comment]
> idk how but I fixed it and I can say that it compiles correctly
> 
> > Actually I think some elements should be initialized outside the main class
> > When a lot of elements are created, main class looks like a mess.
> 
> btw what do you think about this, if you think its okay I could commit it to this pr

I'd say you keep that to another pull request. That would require a lot of refactoring.

**Review by Goldorion — APPROVED** [review]
We should also change the food element for the FabricItemSettings if we use it for the items.

**Pull request merged**
