### PR TITLE
Item Enchantment glint, Tooltips, new gradle versions

### PR DESCRIPTION
**Pull request by BoogieMonster1O1**
This finishes the first page of the Item creation window. And it includes some minor changes that speed things up a bit.

Noticeable Changes : 
+ Added support for Enchantment glint and Tooltips for Items

Minor Changes :
* Upgrade Gradle wrapper to 6.5
* Upgrade loom version to 0.4.25
* Added unnecessary files to the gitignores
* Made `gradlew` executable by `chmod +x ./gradlew` 

I've tested this on both the client and server and it works fine, without any problems. 
This took me nine tries and the first 6 failed because I used the variables from gradle.properties, which didn't work. 

Screenshots:-

Both Tooltip and Glint 

Tooltip, No Glint

Neither Tooltip nor Glint

Glint, No Tooltip

Running it on a multiplayer server
Server

### CODE REVIEW

**Comment by Goldorion** [comment]
Thank you a lot for everything inside this pull request! I've already tried to implement the tool tips in following the Fabric Wiki, but they used the localizations, so it didn't work withMCReator (as they are not supported yet). Anyways thank you for all changes and features you added. It will be in the next update.

**Review by Goldorion — APPROVED** [review]

**Review by Goldorion — COMMENTED** [review]
#7

**Comment by BoogieMonster1O1** [comment]
> Thank you a lot for everything inside this pull request! I've already tried to implement the tool tips in following the Fabric Wiki, but they used the localizations, so it didn't work withMCReator (as they are not supported yet). Anyways thank you for all changes and features you added. It will be in the next update.

I'm glad you liked it. I look forward to seeing these changes merged in the next update.
Toodles!

**Comment by BoogieMonster1O1** [comment]
Also, if you plan on merging these changes, I suggest keeping it open

**Comment by Goldorion** [comment]
> 
> 
> Also, if you plan on merging these changes, I suggest keeping it open

I closed the pull request thinking I could merge the changes after, but no. So I changed the files directly in my workspace. If you want to help to makemore things, you are welcome! :)

**Pull request closed without merging**
